name: PermissionShop
version: 2.4.0 BETA
main: nl.tabuu.permissionshop.PermissionShop
description: This plugin allows players to buy permissions.
authors: [Tabuu]
website: https://www.tabuu.nl
depend: [Vault, TabuuCore]
softdepend: [GroupManager, PermissionsEx, LuckPerms]
api-version: 1.13

commands:
  permissionshop:
    usage: /permissionshop
    description: Opens the shop GUI.
    aliases: [pshop]

  permissionshop add:
    usage: /permissionshop add <name> <price> <permission> [<permission> <permission> ...]
    description: Adds a permission to the shop, the display item will be the item you hold.

  permissionshop remove:
    usage: /permissionshop remove
    description: Opens the removal GUI.

  permissionshop reload:
    usage: /permissionshop reload
    description: Reloads the config.

permissions:
  permissionshop.default:
    description: Allows players to open the GUI.
    default: true

  permissionshop.admin:
    description: Allows players to manage the permission shop.
    default: op